name: Website

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

    - name: Build WASM Module
      run: wasm-pack build --verbose --all-features

    - name: Build web
      run: |
        cd web
        yarn
        yarn run build

    - name: Run linter
      run: |
        cd web
        yarn run lint
